        IMPLICIT NONE
        INTEGER NPTX, NPTY
        INTEGER NXINT, NYINT
        INTEGER NPT, NWORK

        PARAMETER ( NPTX  = 50, NPTY  = 50)
        PARAMETER ( NXINT = NPTX+1, NYINT = NPTY+1)
        PARAMETER ( NPT   = 1000000, NWORK = 1000000)
